davinci:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------

    joint1_position_controller:
      type: effort_controllers/JointPositionController
      joint: roll_22
      pid: {p: 200.0, i: 0, d: 10.0}
    joint2_position_controller:
      type: effort_controllers/JointPositionController
      joint: para22
      pid: {p: 200.0, i: 0, d: 10.0}
    joint3_position_controller:
      type: effort_controllers/JointPositionController
      joint: para23
      pid: {p: 200.0, i: 0, d: 10.0}
    joint4_position_controller:
      type: effort_controllers/JointPositionController
      joint: slide21
      pid: {p: 200.0, i: 0, d: 10.0}
    joint5_position_controller:
      type: effort_controllers/JointPositionController
      joint: instrument2
      pid: {p: 200.0, i: 0, d: 10.0}
    joint6_position_controller:
      type: effort_controllers/JointPositionController
      joint: rotate2
      pid: {p: 200.0, i: 0, d: 10.0}
    joint7_position_controller:
      type: effort_controllers/JointPositionController
      joint: roll2
      pid: {p: 200.0, i: 0, d: 10.0}
    joint8_position_controller:
      type: effort_controllers/JointPositionController
      joint: clip21
      pid: {p: 200.0, i: 0, d: 10.0}
    joint9_position_controller:
      type: effort_controllers/JointPositionController
      joint: clip22
      pid: {p: 200.0, i: 0, d: 10.0}






































































